### ISSUE TITLE
ZendeskSDK.ZDKRequestProvider.GetComments  return nill in native code

### ISSUE THREAD

**Issue by Maksimdz** [zendesk/sdk_unity_plugin#31]
0   CoreFoundation                      0x0000000191a9eff8 <redacted> + 148
	1   libobjc.A.dylib                     0x0000000190500538 objc_exception_throw + 56
	2   CoreFoundation                      0x0000000191aa5ef4 <redacted> + 0
	3   CoreFoundation                      0x0000000191aa2f54 <redacted> + 916
	4   CoreFoundation                      0x000000019199ed4c _CF_forwarding_prep_0 + 92
	5   supertown                           0x000000010076b760 +[ZendeskJSON ZDKCommentToJSON:] + 188
	6   supertown                           0x00000001007699e8 +[ZendeskJSON NSArrayOfZDKCommentsToJSON:] + 368
	7   supertown                           0x0000000100761694 ___zendeskRequestProviderGetCommentsWithRequestId_block_invoke + 152
	8   supertown                           0x0000000100f59acc __60-[ZDKRequestProvider getCommentsWithRequestId:withCallback:]_block_invoke.290 + 252
	9   supertown                           0x0000000100f496d4 __66-[ZDKAPIDispatcher executeRequest:onSuccess:onError:requiresAuth:]_block_invoke + 136
	10  supertown                           0x0000000100f5074c -[ZDKRequestExecutor handleResponse:date:error:request:completionHandler:] + 304
	11  libdispatch.dylib                   0x0000000102f91a50 _dispatch_call_block_and_release + 24
	12  libdispatch.dylib                   0x0000000102f91a10 _dispatch_client_callout + 16
	13  libdispatch.dylib                   0x0000000102f96b78 _dispatch_main_queue_callback_4CF + 1204
	14  CoreFoundation                      0x0000000191a4d0c8 <redacted> + 12
	15  CoreFoundation                      0x0000000191a4ace4 <redacted> + 1572
	16  CoreFoundation                      0x000000019197ada4 CFRunLoopRunSpecific + 424
	17  GraphicsServices                    0x00000001933e4074 GSEventRunModal + 100
	18  UIKit                               0x0000000197c35058 UIApplicationMain + 208
	19  supertown                           0x0000000100073320 main + 208
	20  libdyld.dylib                       0x000000019098959c <redacted> + 4

**Comment by vladkolotvin** [comment]
+1

**Comment by RonanMcH** [comment]
Hey guys,
thanks for reporting this. We will look into it and get back to you guys. We just released 1.10 version of the unity plugin so maybe try upgrading.
Thanks,
Ronan.

**Comment by Maksimdz** [comment]
It still doesn't work. 
By the way  
ZendeskSDK.ZDKConfig._zendeskConfigSetArticlevotingEnabled
ZendeskSDK.ZDKConfig._zendeskConfigSetArticleVotingEnabled
!!!VotingEnabled!!!    Big 'V'
it doesn't compile !!!   )))

+(NSString *)NSArrayOfZDKCommentsToJSON:(NSArray *)items {
      NSMutableArray *results = [[NSMutableArray alloc] init];
      for (**ZDKComment** *comment in items) {
          [results addObject:[ZendeskJSON ZDKCommentToJSON:comment]];
      }
      return [ZendeskJSON serializeJSONObject:[results copy]];
}
i have ZDKCommentWithUser here instead of ZDKComment

**Comment by baz8080** [comment]
@Maksimdz sorry for the delay. The native code is indeed returning `ZDKCommentWithUser`, so the bridge code is out of synch with that.

**Comment by baz8080** [comment]
Fixed in https://github.com/zendesk/sdk_unity_plugin/pull/38
